# Generated by Django 4.2 on 2024-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
