# Generated by Django 4.2 on 2024-07-03 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_saleproduct_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleproduct",
            name="quantity",
        ),
    ]
