# Generated by Django 4.2 on 2024-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_remove_saleproduct_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
