# Generated by Django 4.2 on 2024-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_cartproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartProduct",
        ),
    ]
